import type { Metadata } from "next"
import { Oswald, Roboto } from "next/font/google"
import "./globals.css"
import { NavbarLayout, NavbarLink } from "@repo/ui/Navbar"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { PiCrownSimpleFill } from "react-icons/pi"
import LightningButton from "@repo/ui/LightningButton"
import MainContentFrame from "@repo/ui/MainContentFrame"
import { ClerkProvider, SignUpButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import Link from "next/link"
import { SearchButton } from "@/components/Search"
import { currentUser } from "@clerk/nextjs/server"
import { Analytics } from "@vercel/analytics/next"
import { FaUserGroup } from "react-icons/fa6"
import { safeSubstring } from "@repo/ui/helpers"

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "BLUEWARD (* ^ ω ^)つロ",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      appearance={{
        theme: dark,
        variables: { colorPrimary: "#3aa4fc" },
      }}
    >
      <html lang="en">
        <body className={`${oswald.variable} ${roboto.className} ${roboto.variable}`}>
          <SpeedInsights />
          <Analytics />

          <MainContentFrame Navbar={<Navbar />} backgroundPatternUrl="/grid.svg" backgroundPatternSize={512}>
            {children}
          </MainContentFrame>
        </body>
      </html>
    </ClerkProvider>
  )
}

function Navbar() {
  return (
    <NavbarLayout signInButtons={<SignInButtons />}>
      <NavbarLink
        href="/leaderboard/kills"
        icon={<PiCrownSimpleFill className="inline-block text-blue-500 rotate-35" size={14} />}
      >
        Leaderboards
      </NavbarLink>

      <LightningButton href="/fightclub">Fight Club</LightningButton>
    </NavbarLayout>
  )
}

async function SignInButtons() {
  const user = await currentUser()
  const puuid = user?.privateMetadata.puuid as string | undefined

  return (
    <div className="flex items-center gap-4">
      <SignedOut>
        <SignUpButton>
          <div className="flex items-center gap-2 rounded-xl px-6 py-1.5 border border-blue-500 bg-blue-600/80 hover:bg-blue-600 transition-colors duration-200">
            <FaUserGroup size={14} />
            <span className="text-sm uppercase">Sign Up</span>
          </div>
        </SignUpButton>
      </SignedOut>
      <SignedIn>
        {user && user.privateMetadata.role === "admin" && (
          <Link
            href="/import"
            className="flex items-center gap-2 rounded-xl px-6 py-1.5 border border-blue-500 bg-blue-600/80 hover:bg-blue-600 transition-colors duration-200"
          >
            <span className="text-sm uppercase">Import Game</span>
          </Link>
        )}

        <UserButton />

        {puuid && (
          <Link
            href={`/player/${safeSubstring(puuid, 0, 20)}`}
            className="flex items-center gap-2 rounded-xl px-3 py-1.5 border border-blue-500 bg-blue-600/80 hover:bg-blue-600 transition-colors duration-200"
          >
            <span className="text-sm">Go to Linked Account</span>
            <FaUserGroup size={15} />
          </Link>
        )}
      </SignedIn>

      <SearchButton />
    </div>
  )
}
