import type { Metadata } from "next"
import { Oswald, Roboto } from "next/font/google"
import "./globals.css"
import { NavbarLayout, NavbarLink } from "@repo/ui/Navbar"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { PiCrownSimpleFill } from "react-icons/pi"
import LightningButton from "@repo/ui/LightningButton"
import MainContentFrame from "@repo/ui/MainContentFrame"
import { FaPencilAlt } from "react-icons/fa"
import LetterPopup from "@/components/LetterPopup"

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Blueward (* ^ ω ^)つロ",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${roboto.className}`}>
        <SpeedInsights />

        <LetterPopup src={"/postcard.webp"} />

        <MainContentFrame Navbar={<Navbar />} backgroundPatternUrl="/grid.svg" backgroundPatternSize={512}>
          {children}
        </MainContentFrame>
      </body>
    </html>
  )
}

function Navbar() {
  return (
    <NavbarLayout>
      <NavbarLink
        href="/leaderboard/kills"
        icon={<PiCrownSimpleFill className="inline-block text-blue-500 rotate-35" size={14} />}
      >
        Leaderboards
      </NavbarLink>

      <NavbarLink href="/markets" icon={<FaPencilAlt className="inline-block text-blue-500 rotate-270" size={14} />}>
        Predictions
      </NavbarLink>

      <LightningButton href="/fightclub">Fight Club</LightningButton>
    </NavbarLayout>
  )
}
