import type { Metadata } from "next"
import { Oswald, Roboto } from "next/font/google"
import "./globals.css"
import Navbar from "../components/Navbar"
import { SpeedInsights } from "@vercel/speed-insights/next"
import Footer from "@/components/Footer"
import MarketsMarqueePopup from "@/components/MarketsMarqueePopup"

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Blueward (* ^ ω ^)つロ",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${roboto.className}`}>
        <SpeedInsights />

        <div className="bg-zinc-900 min-h-screen flex flex-col">
          <Navbar />

          <div
            className="flex-1 mx-2 mb-2 p-4 rounded-lg bg-zinc-950 border
                        border-zinc-800 shadow-[0_0_60px_rgba(96,165,250,0.35)]"
          >
            <div className="w-full max-w-7xl mx-auto">{children}</div>
          </div>

          <div className="mt-2">
            <Footer />
          </div>
        </div>

        <MarketsMarqueePopup />
      </body>
    </html>
  )
}
