import type { Metadata } from "next"
import { Oswald, Roboto } from "next/font/google"
import "./globals.css"
import MainContentFrame from "@repo/ui/MainContentFrame"
import { NavbarLayout, NavbarLink } from "@repo/ui/Navbar"

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Blueward (* ^ ω ^)つロ",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${roboto.className}`}>
        <MainContentFrame Navbar={<Navbar />}>{children}</MainContentFrame>
      </body>
    </html>
  )
}

function Navbar() {
  return <NavbarLayout />
}
